# Generated by Django 4.0.2 on 2022-02-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_app', '0002_alter_ingredients_title_alter_lunch_title_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='lunch',
        ),
    ]
